<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DM-DT16" failures="1" tests="3" name="Crud Test" time="94.064" errors="0" timestamp="2023-03-02T10:16:14 IST">
  <testcase classname="eidsa.EidsaTest.Test.EidsaCrudTest" name="siteCrud" time="25.516"/>
  <testcase classname="eidsa.EidsaTest.Test.EidsaCrudTest" name="studyCrud" time="24.983">
    <failure type="java.lang.AssertionError" message="expected [Study ID already exists.] but found [Study updated successfully.]">
      <![CDATA[java.lang.AssertionError: expected [Study ID already exists.] but found [Study updated successfully.]
at eidsa.EidsaTest.Test.EidsaCrudTest.studyCrud(EidsaCrudTest.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- studyCrud -->
  <testcase classname="eidsa.EidsaTest.Test.EidsaCrudTest" name="subjectCrud" time="27.794"/>
</testsuite> <!-- Crud Test -->
